### ISSUE TITLE
Certain video links fail to load

### ISSUE THREAD

**Issue by sakuramboo** [dethfeet/plugin.video.retrowaretv#1]
It seems that only the videos hosted by BlipTV load, but non of the others. Here is a snippet from the logs.

08:29:22 T:2902447200  NOTICE: http://retrowaretv.com/trashed-classics-cry-of-fear/
08:29:25 T:3047514112  NOTICE: COMXPlayer: Opening:
08:29:25 T:3047514112 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
08:29:25 T:3047514112  NOTICE: CXBMCRenderManager::ResetRenderBuffer - using 5 render buffers
08:29:25 T:2725246048  NOTICE: Thread COMXPlayer start, auto delete: false
08:29:25 T:2725246048  NOTICE: Creating InputStream
08:29:25 T:2725246048   ERROR: Error on dvdnav_open
08:29:25 T:2725246048   ERROR: COMXPlayer::OpenInputStream - error opening []
08:29:25 T:2725246048  NOTICE: COMXPlayer::OnExit()
08:29:25 T:2725246048  NOTICE: COMXPlayer::OnExit() deleting input stream
08:29:25 T:3047514112   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.retrowaretv/?action=playEpisode&link=http%3A%2F%2Fretrowaretv.com%2Ftrashed-classics-cry-of-fear%2F]
08:29:25 T:2725246048  NOTICE: Thread Background Loader start, auto delete: false
08:29:25 T:2920023136  NOTICE: 1Channel: Playback Stopped
08:29:25 T:2920023136  NOTICE: 1Channel: Service: Resetting...
08:29:25 T:3047514112  NOTICE: OMXClock using video as reference

**Comment by sakuramboo** [comment]
Latest update fixed this.

Thanks.

**Comment by dethfeet** [comment]
Yes, thanks for reporting and sorry for not responding earlier. If something else fails just let me know :-)
